export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAILURE = 'CATEGORY_FAILURE';


export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAILURE = 'GET_SINGLE_PRODUCT_FAILURE';


export const ADD_PRODUCT_CART_REQUEST = 'ADD_PRODUCT_CART_REQUEST';
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS';
export const ADD_PRODUCT_CART_FAILURE = 'ADD_PRODUCT_CART_FAILURE';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';



export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const REMOVE_PRODUCT_FROM_CART_REQUEST = 'REMOVE_PRODUCT_FROM_CART_REQUEST';
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = 'REMOVE_PRODUCT_FROM_CART_SUCCESS';
export const REMOVE_PRODUCT_FROM_CART_FAILURE = 'REMOVE_PRODUCT_FROM_CART_FAILURE';



export const ADD_PRODUCT_ORDER_REQUEST = 'ADD_PRODUCT_ORDER_REQUEST';
export const ADD_PRODUCT_ORDER_SUCCESS = 'ADD_PRODUCT_ORDER_SUCCESS';
export const ADD_PRODUCT_ORDER_FAILURE = 'ADD_PRODUCT_ORDER_FAILURE';

export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAILURE = 'EMPTY_CART_FAILURE';


export const CART_COUNTER_REQUEST = 'CART_COUNTER_REQUEST';
export const CART_COUNTER_SUCCESS = 'CART_COUNTER_SUCCESS';
export const CART_COUNTER_FAILURE = 'CART_COUNTER_FAILURE';

export const PRODUCT_QUANTITY = 'PRODUCT_QUANTITY';


export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const REMOVE_PRODUCT_FROM_ORDER_REQUEST = 'REMOVE_PRODUCT_FROM_ORDER_REQUEST';
export const REMOVE_PRODUCT_FROM_ORDER_SUCCESS = 'REMOVE_PRODUCT_FROM_ORDER_SUCCESS';
export const REMOVE_PRODUCT_FROM_ORDER_FAILURE = 'REMOVE_PRODUCT_FROM_ORDER_FAILURE';

